# Generated by Django 4.1.8 on 2023-04-25 07:31

from django.db import migrations, models
import django.db.models.deletion
import django_jalali.db.models
import uuid
import visit.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('medical_education_number', models.CharField(max_length=50, verbose_name='شماره نظام پزشکی')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images/', verbose_name='عکس')),
                ('address', models.CharField(max_length=200, verbose_name='آدرس')),
            ],
            options={
                'verbose_name': 'دکتر',
                'verbose_name_plural': 'دکتر ها',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(max_length=15, verbose_name='تلفن همراه')),
            ],
            options={
                'verbose_name': 'بیمار',
                'verbose_name_plural': 'بیماران',
            },
        ),
        migrations.CreateModel(
            name='Speciality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='نوع تخصص')),
            ],
            options={
                'verbose_name': 'تخصص',
                'verbose_name_plural': 'تخصص',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', visit.models.TimeFieldWithoutSeconds(verbose_name='ساعت شروع')),
                ('end_time', visit.models.TimeFieldWithoutSeconds(verbose_name='ساعت پایان')),
            ],
            options={
                'verbose_name': 'شیفت',
                'verbose_name_plural': 'شیفت ها',
            },
        ),
        migrations.CreateModel(
            name='WeeklySchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.PositiveSmallIntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], verbose_name='روز')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.doctor', verbose_name='دکتر')),
                ('time_slots', models.ManyToManyField(to='visit.timeslot', verbose_name='شیفت')),
            ],
            options={
                'verbose_name': 'برنامه هفتگی',
                'verbose_name_plural': 'برنامه هفتگی',
            },
        ),
        migrations.AddField(
            model_name='doctor',
            name='speciality',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.speciality', verbose_name='نوع تخصص'),
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', django_jalali.db.models.jDateField(verbose_name='تاریخ')),
                ('tracking_number', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='کد رهگیری')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.doctor', verbose_name='نام دکتر')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.patient', verbose_name='نام بیمار')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visit.timeslot', verbose_name='شیفت')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
            },
        ),
    ]
