# Generated by Django 4.1.8 on 2023-04-25 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together={('doctor', 'day_of_week')},
        ),
    ]
