# Generated by Django 4.1.8 on 2023-04-29 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0004_alter_appointment_tracking_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='tracking_number',
            field=models.PositiveIntegerField(blank=True, editable=False, null=True, unique=True, verbose_name='کد رهگیری'),
        ),
    ]
