# Generated by Django 4.1.8 on 2023-04-30 10:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0005_alter_appointment_tracking_number'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='weeklyschedule',
            unique_together=set(),
        ),
    ]
