# Generated by Django 4.1.8 on 2023-04-30 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0006_alter_weeklyschedule_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='weeklyschedule',
            name='flag',
            field=models.BooleanField(default=True, verbose_name='وضعیت'),
        ),
    ]
