# Generated by Django 4.1.8 on 2023-05-01 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visit', '0007_weeklyschedule_flag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyschedule',
            name='flag',
        ),
    ]
